env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  ignore:
  - goos: darwin
    goarch: 386
archives:
- replacements:
    darwin: macOS
    386: i386
nfpms:
- replacements:
    darwin: macOS 
    386: i386
  homepage: https://github.com/eugene-babichenko/zpm
  description: Simple and fast zsh plugins manager
  license: MIT
  formats:
  - deb
  - rpm
  recommends:
  - zsh
brews:
- github:
    owner: eugene-babichenko
    name: homebrew-tap
  homepage: https://github.com/eugene-babichenko/zpm
  description: Simple and fast zsh plugins manager
snapcrafts:
- id: zpm
  builds:
  - zpm
  name: zpm
  summary: Simple and fast zsh plugins manager
  description: Simple and fast zsh plugins manager
  grade: stable
  confinement: strict
  license: MIT
  base: bare
  apps:
    zpm:
      plugs: ["network", "zpm-files"]
  plugs:
    zpm-files:
      interface: personal-files
      read:
      - $HOME/.zpm.yaml
      - $HOME/.zpm_plugins
      write:
      - $HOME/.zpm.yaml
      - $HOME/.zpm_plugins
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
