language: go

go:
  - 1.12.x

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/gopath

script:
  - GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt
